version: "3"
services:
  
  ui:
   build:
      context: ./frontend
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: frontend
   networks:
    -  cilist-networks
   volumes:
    -  ./frontend/src:/usr/app/src
    -  ./frontend/build:/usr/app/build
   depends_on:
    - backend
   environment:
    REACT_APP_BACKEND_URL: http://localhost:6000
   stdin_open: true
   tty: true

  db:
    image: triagungtio/cilist-db 
    ports:
      - 3300:3306
    container_name: mysql
    logging:
        driver: journald
        options:
            tag: mytag
    networks:
      - cilist-networks
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile.dev
   ports:
     - 6000:6000
   container_name: backend
   logging:
      driver: journald
      options:
         tag: mytag2
   networks:
     - cilist-networks
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - db
   environment:
      - BASE_URL_PORT=6000
      - MYSQL_ROOT_PASSWORD=people
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

networks:
  cilist-networks:
    
volumes:
  mysql-data:
